//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopaceticSoftware.CodeGenerator.StarterKit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopaceticSoftware.CodeGenerator.StarterKit.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generator Pipeline can not execute when source file has errors.  Correct any errors and re-run Code Generator..
        /// </summary>
        internal static string ErrorSourceFileHasErrors {
            get {
                return ResourceManager.GetString("ErrorSourceFileHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project at [{0}] has not been parsed or could not be found. .
        /// </summary>
        internal static string ExceptionCouldNotFindProjectWithFullName {
            get {
                return ResourceManager.GetString("ExceptionCouldNotFindProjectWithFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] Added Class: [{1}].
        /// </summary>
        internal static string VisualStudioEventClassAddedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventClassAddedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] Opened Class: [{1}].
        /// </summary>
        internal static string VisualStudioEventClassOpenedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventClassOpenedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] Removed Class: [{1}].
        /// </summary>
        internal static string VisualStudioEventClassRemovedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventClassRemovedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] Renamed Class from [{1}] to [{2}].
        /// </summary>
        internal static string VisualStudioEventClassRenamedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventClassRenamedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] Saved Class: [{1}].
        /// </summary>
        internal static string VisualStudioEventClassSavedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventClassSavedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Added: [{0}].
        /// </summary>
        internal static string VisualStudioEventProjectAddedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventProjectAddedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] Added Reference: [{1}].
        /// </summary>
        internal static string VisualStudioEventProjectReferenceAddedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventProjectReferenceAddedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] Removed Reference: [{1}].
        /// </summary>
        internal static string VisualStudioEventProjectReferenceRemovedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventProjectReferenceRemovedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Removed: [{0}].
        /// </summary>
        internal static string VisualStudioEventProjectRemovedDebugString {
            get {
                return ResourceManager.GetString("VisualStudioEventProjectRemovedDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Resolve Class: {0}.
        /// </summary>
        internal static string WarningFailedToResolveClass {
            get {
                return ResourceManager.GetString("WarningFailedToResolveClass", resourceCulture);
            }
        }
    }
}
