//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.1.12.350
//      for file D:\Projects\sandbox\pMixins\pMixins.Mvc.Recipes\AbstractMixin\AbstractMixin.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.AbstractMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public partial class AbstractMixinExample : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin.IPrinterMixinRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin>
	{
		[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public readonly __pMixinAutoGenerated.pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin.PrinterMixinMasterWrapper pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin;
			public __Mixins (AbstractMixinExample host)
			{
				pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin.PrinterMixinMasterWrapper> ((global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin.IPrinterMixinRequirements)host);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (AbstractMixinExample host)
			{
				pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin.__ActivateMixinDependencies (host);
			}
		}
		private __Mixins _____mixins;
		private __Mixins ___mixins {
			get {
				if (null == _____mixins) {
					lock (__Mixins.____Lock) {
						if (null == _____mixins) {
							_____mixins = new __Mixins (this);
							_____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return _____mixins;
			}
		}
		[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
		private sealed class __pMixinAutoGenerated
		{
			[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
			public sealed class pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin
			{
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
				public sealed class PrinterMixinMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin.PrinterMixinAbstractWrapper _mixinInstance;
					public PrinterMixinMasterWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin.IPrinterMixinRequirements mixinInstance)
					{
						_mixinInstance = base.TryActivateMixin<global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin.PrinterMixinAbstractWrapper> (mixinInstance);
						base.Initialize (mixinInstance, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (AbstractMixinExample target)
					{
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::System.String PrintName ()
					{
						return base.ExecuteMethod ("PrintName", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {

						}, () => _mixinInstance.PrintName ());
					}
					internal global::System.String Name {
						get {
							return base.ExecutePropertyGet ("Name", () => _mixinInstance.Name);
						}
					}
				}
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::System.String PrintName ()
		{
			return ___mixins.pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin.PrintName ();
		}
		public virtual global::System.String Name {
			get {
				return ___mixins.pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin.Name;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin (AbstractMixinExample target) {
			return target.___mixins.pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin._mixinInstance;
		}
		global::pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin>.MixinInstance {
			get {
				return ___mixins.pMixins_Mvc_Recipes_AbstractMixin_PrinterMixin._mixinInstance;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public interface IPrinterMixinRequirements
	{
		global::System.String NameImplementation {
			get;
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public abstract class PrinterMixinProtectedMembersWrapper : global::pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin
	{
		public PrinterMixinProtectedMembersWrapper () : base ()
		{
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public class PrinterMixinAbstractWrapper : PrinterMixinProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin.IPrinterMixinRequirements _target;
		public PrinterMixinAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AbstractMixin.AbstractMixinExample.pMixins.Mvc.Recipes.AbstractMixin.PrinterMixin.IPrinterMixinRequirements target)
		{
			_target = target;
		}
		public override global::System.String Name {
			get {
				return _target.NameImplementation;
			}
		}
	}
}
