//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.5.1.379
//      for file pMixins\pMixins.Mvc.Recipes\DependencyInjection\DependencyInjectionMixin.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.DependencyInjection
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.5.1.379")]
	public partial class DependencyInjectionMixinExample : pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin.IDependencyInjectionMixinRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin.DependencyInjectionMixinMasterWrapper pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin;
			public __Mixins (DependencyInjectionMixinExample target)
			{
				pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin.DependencyInjectionMixinMasterWrapper> ((pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin.IDependencyInjectionMixinRequirements)target);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample target)
			{
				pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			public sealed class pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin
			{
				public class DependencyInjectionMixinMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public DependencyInjectionMixinMasterWrapper (pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin.IDependencyInjectionMixinRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin.DependencyInjectionMixinAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin _mixinInstance;
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample target)
					{
					}
					internal global::System.String DependencyName {
						get {
							return base.ExecutePropertyGet ("DependencyName", () => _mixinInstance.DependencyName);
						}
					}
				}
			}
		}
		private __Mixins ____mixins;
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		global::pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin>.MixinInstance {
			get {
				return __mixins.pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin._mixinInstance;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin (DependencyInjectionMixinExample target) {
			return target.__mixins.pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin._mixinInstance;
		}
		public global::System.String DependencyName {
			get {
				return __mixins.pMixins_Mvc_Recipes_DependencyInjection_DependencyInjectionMixin.DependencyName;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.__Shared
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.5.1.379")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.5.1.379")]
	public interface IDependencyInjectionMixinRequirements : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin
{
	public abstract class DependencyInjectionMixinProtectedMembersWrapper : global::pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin
	{
		public DependencyInjectionMixinProtectedMembersWrapper (global::pMixins.Mvc.Recipes.DependencyInjection.IDependency dependency) : base (dependency)
		{
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin
{
	public class DependencyInjectionMixinAbstractWrapper : DependencyInjectionMixinProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin.IDependencyInjectionMixinRequirements _target;
		public DependencyInjectionMixinAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixinExample.pMixins.Mvc.Recipes.DependencyInjection.DependencyInjectionMixin.IDependencyInjectionMixinRequirements target, global::pMixins.Mvc.Recipes.DependencyInjection.IDependency dependency) : base (dependency)
		{
			_target = target;
		}
	}
}
