//----------------------------------------------------------------------- 
// <copyright file="BasicInterceptorSpec.cs" company="Copacetic Software"> 
// Copyright (c) Copacetic Software.  
// <author>Philip Pittle</author> 
// <date>Thursday, February 20, 2014 11:12:49 PM</date> 
// Licensed under the Apache License, Version 2.0,
// you may not use this file except in compliance with this License.
//  
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright> 
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CopaceticSoftware.pMixins.CodeGenerator.Tests.IntegrationTests.CompileTests.Interceptors;

namespace CopaceticSoftware.pMixins.TheorySandbox.COVERED.Interceptors.BasicInterceptor
{ //Can specify activator with attribute?
    /// <summary>
    /// Covered in:
    ///     <see cref="BasicInterceptorTest"/>
    /// </summary>
    public class MixinInterceptor : IMixinInterceptor
    {
        public static int InitializedCount = 0;
        public static int BeforeMethodInvocationCount = 0;
        public static int AfterMethodInvocationCount = 0;
        public static int BeforePropertyGetInvocationCount = 0;
        public static int AfterPropertyGetInvocationCount = 0;
        public static int BeforePropertySetInvocationCount = 0;
        public static int AfterPropertySetInvocationCount = 0;


        public void OnMixinInitialized(object sender, InterceptionEventArgs args)
        {
            InitializedCount++;
        }

        public void OnBeforeMethodInvocation(object sender, MethodEventArgs eventArgs)
        {
            BeforeMethodInvocationCount++;
        }

        public void OnAfterMethodInvocation(object sender, MethodEventArgs eventArgs)
        {
            AfterMethodInvocationCount++;
        }

        public void OnBeforePropertyInvocation(object sender, PropertyEventArgs eventArgs)
        {
            if (eventArgs.IsGet)
                BeforePropertyGetInvocationCount++;
            else
                BeforePropertySetInvocationCount++;
        }

        public void OnAfterPropertyInvocation(object sender, PropertyEventArgs eventArgs)
        {
            if (eventArgs.IsGet)
                AfterPropertyGetInvocationCount++;
            else
                AfterPropertySetInvocationCount++;
        }
    }

//Can a mixin specify it's activator?
    public class Mixin
    {
        public string Method(int i)
        {
            return i.ToString();
        }

        public string Property { get; set; }
    }

    [BasicMixin(Target = typeof(Mixin), Interceptors = new Type[] { typeof(MixinInterceptor)})]
    public partial class BasicInterceptorSpec
    {}

/*/////////////////////////////////////////
/// Generated Code
/////////////////////////////////////////*/

    public partial class BasicInterceptorSpec
    {
        private class __pMixinAutoGenerated
        {
            public class CopaceticSoftware_pMixin_TheorySandbox_Interceptors_BasicInterceptor_Mixin
            {
                //don't need protected wrapper

                //don't need abstract wrapper

                public sealed class MasterWrapper : MasterWrapperBase
                {
                    public readonly Mixin Mixin;
                    
                    public MasterWrapper(BasicInterceptorSpec target)
                    {
                        this.Mixin = new Mixin();

                        base.Initialize(target, Mixin,
                            new List<IMixinInterceptor>
                            {
                                //Need custom activator?
                                new DefaultMixinActivator().CreateInstance<MixinInterceptor>()
                            });
                    }

                    public string Method(int i)
                    {
                        return base.ExecuteMethod(
                            "Method",
                            new List<Parameter>
                            {
                                new Parameter
                                {
                                    Name = "i",
                                    Type = typeof (int),
                                    Value = i
                                }
                            },
                            () => Mixin.Method(i));
                    }

                    public string Property
                    {
                        get
                        {
                            return base.ExecutePropertyGet("Property", () => Mixin.Property);

                            
                        }
                        set
                        {
                            ExecutePropertySet("Property", value, v=> Mixin.Property = v);
                        }
                    }
                }
            }
        }

        private sealed partial class __Mixins
        {
            public static readonly global::System.Object ____Lock = new global::System.Object();

            public readonly __pMixinAutoGenerated.CopaceticSoftware_pMixin_TheorySandbox_Interceptors_BasicInterceptor_Mixin.MasterWrapper MixinMasterWrapper;

            public __Mixins(BasicInterceptorSpec target)
            {
                this.MixinMasterWrapper =
                    new DefaultMixinActivator()
                        .CreateInstance<__pMixinAutoGenerated.CopaceticSoftware_pMixin_TheorySandbox_Interceptors_BasicInterceptor_Mixin.MasterWrapper>(
                            target);
            }
        }

        private __Mixins _____mixins;
        private __Mixins ___mixins
        {
            get
            {
                if (null == _____mixins)
                {
                    lock (__Mixins.____Lock)
                    {
                        if (null == _____mixins)
                        {
                            _____mixins = new __Mixins(this);
                        }
                    }
                }
                return _____mixins;
            }
        }

        public string Method(int i)
        {
            return ___mixins.MixinMasterWrapper.Method(i);
        }

        public string Property
        {
            get { return ___mixins.MixinMasterWrapper.Property; }
            set { ___mixins.MixinMasterWrapper.Property = value; }
        }
    }
}