//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.1.12.328
//      for file D:\Projects\sandbox\pMixins\pMixins.Mvc.Recipes\BasicMixin\BasicMixin.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.BasicMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
	public partial class BasicMixinExample : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin.IAnswerToTheUniverseMixinRequirements, global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin.IHelloWorldMixinRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin>
	{
		[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public readonly __pMixinAutoGenerated.pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin.AnswerToTheUniverseMixinMasterWrapper pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin;
			public readonly __pMixinAutoGenerated.pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin.HelloWorldMixinMasterWrapper pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin;
			public __Mixins (BasicMixinExample host)
			{
				pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin.AnswerToTheUniverseMixinMasterWrapper> ((global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin.IAnswerToTheUniverseMixinRequirements)host);
				pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin.HelloWorldMixinMasterWrapper> ((global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin.IHelloWorldMixinRequirements)host);
			}
		}
		private __Mixins _____mixins;
		private __Mixins ___mixins {
			get {
				if (null == _____mixins) {
					lock (__Mixins.____Lock) {
						if (null == _____mixins) {
							_____mixins = new __Mixins (this);
						}
					}
				}
				return _____mixins;
			}
		}
		[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
		private sealed class __pMixinAutoGenerated
		{
			[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
			public sealed class pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin
			{
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
				public abstract class AnswerToTheUniverseMixinProtectedMembersWrapper : global::pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin
				{
					public AnswerToTheUniverseMixinProtectedMembersWrapper () : base ()
					{
					}
				}
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
				public class AnswerToTheUniverseMixinAbstractWrapper : AnswerToTheUniverseMixinProtectedMembersWrapper
				{
					private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin.IAnswerToTheUniverseMixinRequirements _target;
					public AnswerToTheUniverseMixinAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin.IAnswerToTheUniverseMixinRequirements target)
					{
						_target = target;
					}
				}
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
				public sealed class AnswerToTheUniverseMixinMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public readonly global::pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin _mixinInstance;
					public AnswerToTheUniverseMixinMasterWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin.IAnswerToTheUniverseMixinRequirements mixinInstance)
					{
						_mixinInstance = base.TryActivateMixin<__pMixinAutoGenerated.pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin.AnswerToTheUniverseMixinAbstractWrapper> (mixinInstance);
						base.Initialize (mixinInstance, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::System.Int32 AnswerToTheUniverse ()
					{
						return base.ExecuteMethod ("AnswerToTheUniverse", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {

						}, () => _mixinInstance.AnswerToTheUniverse ());
					}
				}
			}
			[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
			public sealed class pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin
			{
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
				public abstract class HelloWorldMixinProtectedMembersWrapper : global::pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin
				{
					public HelloWorldMixinProtectedMembersWrapper () : base ()
					{
					}
				}
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
				public class HelloWorldMixinAbstractWrapper : HelloWorldMixinProtectedMembersWrapper
				{
					private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin.IHelloWorldMixinRequirements _target;
					public HelloWorldMixinAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin.IHelloWorldMixinRequirements target)
					{
						_target = target;
					}
				}
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
				public sealed class HelloWorldMixinMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public readonly global::pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin _mixinInstance;
					public HelloWorldMixinMasterWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin.IHelloWorldMixinRequirements mixinInstance)
					{
						_mixinInstance = base.TryActivateMixin<__pMixinAutoGenerated.pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin.HelloWorldMixinAbstractWrapper> (mixinInstance);
						base.Initialize (mixinInstance, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::System.String GetHelloWorld ()
					{
						return base.ExecuteMethod ("GetHelloWorld", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {

						}, () => _mixinInstance.GetHelloWorld ());
					}
				}
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::System.Int32 AnswerToTheUniverse ()
		{
			return ___mixins.pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin.AnswerToTheUniverse ();
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin (BasicMixinExample target) {
			return target.___mixins.pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin._mixinInstance;
		}
		global::pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin>.MixinInstance {
			get {
				return ___mixins.pMixins_Mvc_Recipes_BasicMixin_AnswerToTheUniverseMixin._mixinInstance;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::System.String GetHelloWorld ()
		{
			return ___mixins.pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin.GetHelloWorld ();
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin (BasicMixinExample target) {
			return target.___mixins.pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin._mixinInstance;
		}
		global::pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin>.MixinInstance {
			get {
				return ___mixins.pMixins_Mvc_Recipes_BasicMixin_HelloWorldMixin._mixinInstance;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.AnswerToTheUniverseMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
	public interface IAnswerToTheUniverseMixinRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.BasicMixin.BasicMixinExample.pMixins.Mvc.Recipes.BasicMixin.HelloWorldMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.328")]
	public interface IHelloWorldMixinRequirements
	{
	}
}
