//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.6.0.457
//      for file pMixins\pMixins.Mvc.Recipes\SpecificMixinConstructor\SpecificMixinConstructor.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.SpecificMixinConstructor
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public partial class SpecificMixinConstructor : pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin.IMixinRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin>, CopaceticSoftware.pMixins.Infrastructure.IMixinConstructorRequirement<global::pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin.MixinMasterWrapper pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin;
			public __Mixins (SpecificMixinConstructor target)
			{
				pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin.MixinMasterWrapper> ((pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin.IMixinRequirements)target);
			}
			[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor target)
			{
				pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			public sealed class pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin
			{
				public class MixinMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public MixinMasterWrapper (pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin.IMixinRequirements target)
					{
						_mixinInstance = ((global::CopaceticSoftware.pMixins.Infrastructure.IMixinConstructorRequirement<global::pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin>)target).InitializeMixin ();
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ConstructorUsed {
						get {
							return base.ExecutePropertyGet ("ConstructorUsed", () => _mixinInstance.ConstructorUsed);
						}
					}
				}
			}
		}
		private __Mixins ____mixins;
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin>.MixinInstance {
			get {
				return __mixins.pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin (SpecificMixinConstructor target) {
			return target.__mixins.pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin._mixinInstance;
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		public global::System.String ConstructorUsed {
			get {
				return __mixins.pMixins_Mvc_Recipes_SpecificMixinConstructor_Mixin.ConstructorUsed;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.__Shared
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface IMixinRequirements : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin
{
	public abstract class MixinProtectedMembersWrapper : global::pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin
	{
		public MixinProtectedMembersWrapper (global::System.String constructorName) : base (constructorName)
		{
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin
{
	public class MixinAbstractWrapper : MixinProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin.IMixinRequirements _target;
		public MixinAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.SpecificMixinConstructor.SpecificMixinConstructor.pMixins.Mvc.Recipes.SpecificMixinConstructor.Mixin.IMixinRequirements target, global::System.String constructorName) : base (constructorName)
		{
			_target = target;
		}
	}
}
