//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.6.0.457
//      for file pMixins\pMixins.Mvc.Recipes\AspectOrientedProgramming\AspectOrientedProgramming.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.AspectOrientedProgramming
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public partial class AspectOrientedProgramming : pMixins.AutoGenerated.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl.IAspectOrientedProgramming_AspectOrientedProgrammingImplRequirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl.AspectOrientedProgramming_AspectOrientedProgrammingImplMasterWrapper pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl;
			public __Mixins (AspectOrientedProgramming target)
			{
				pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl.AspectOrientedProgramming_AspectOrientedProgrammingImplMasterWrapper> ((pMixins.AutoGenerated.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl.IAspectOrientedProgramming_AspectOrientedProgrammingImplRequirements)target);
			}
			[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming target)
			{
				pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
			public sealed class pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl
			{
				public abstract class AspectOrientedProgramming_AspectOrientedProgrammingImplProtectedMembersWrapper : global::pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl
				{
				}
				public class AspectOrientedProgramming_AspectOrientedProgrammingImplAbstractWrapper : AspectOrientedProgramming_AspectOrientedProgrammingImplProtectedMembersWrapper
				{
					private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl.IAspectOrientedProgramming_AspectOrientedProgrammingImplRequirements _target;
					public AspectOrientedProgramming_AspectOrientedProgrammingImplAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl.IAspectOrientedProgramming_AspectOrientedProgrammingImplRequirements target) : base ()
					{
						_target = target;
					}
				}
				public class AspectOrientedProgramming_AspectOrientedProgrammingImplMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public AspectOrientedProgramming_AspectOrientedProgrammingImplMasterWrapper (pMixins.AutoGenerated.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl.IAspectOrientedProgramming_AspectOrientedProgrammingImplRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<AspectOrientedProgramming_AspectOrientedProgrammingImplAbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {
							global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<global::pMixins.Mvc.Recipes.AspectOrientedProgramming.LoggingAspect> (),
							global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<global::pMixins.Mvc.Recipes.AspectOrientedProgramming.NullParameterAspect> ()
						});
					}
					public global::pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public global::System.String Stringify (global::System.Int32 i)
					{
						return base.ExecuteMethod ("Stringify", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "i",
								Type = typeof(global::System.Int32),
								Value = i
							}
						}, () => _mixinInstance.Stringify (i));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public global::System.Object ExampleMethod (global::System.Object o)
					{
						return base.ExecuteMethod ("ExampleMethod", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "o",
								Type = typeof(global::System.Object),
								Value = o
							}
						}, () => _mixinInstance.ExampleMethod (o));
					}
				}
			}
		}
		private __Mixins ____mixins;
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl>.MixinInstance {
			get {
				return __mixins.pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::System.String Stringify (global::System.Int32 i)
		{
			return __mixins.pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl.Stringify (i);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::System.Object ExampleMethod (global::System.Object o)
		{
			return __mixins.pMixins_Mvc_Recipes_AspectOrientedProgramming_AspectOrientedProgramming_AspectOrientedProgrammingImpl.ExampleMethod (o);
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.__Shared
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.AspectOrientedProgrammingImpl
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface IAspectOrientedProgramming_AspectOrientedProgrammingImplRequirements : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.AspectOrientedProgramming.AspectOrientedProgramming.__Shared.ISharedRequirements
	{
	}
}
