//----------------------------------------------------------------------- 
// <copyright file="GenerateAutoGeneratedContainerClass.cs" company="Copacetic Software"> 
// Copyright (c) Copacetic Software.  
// <author>Philip Pittle</author> 
// <date>Friday, February 28, 2014 2:54:00 PM</date> 
// Licensed under the Apache License, Version 2.0,
// you may not use this file except in compliance with this License.
//  
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright> 
//-----------------------------------------------------------------------

using CopaceticSoftware.Common.Patterns;
using ICSharpCode.NRefactory.CSharp;

namespace CopaceticSoftware.pMixins.CodeGenerator.Pipelines.GenerateCode.Steps
{
    /// <summary>
    /// Generates like:
    /// <code>
    /// <![CDATA[
    /// private class __pMixinAutoGenerated
    /// {
    /// }    
    /// ]]>
    /// </code>
    /// </summary>
    public class GenerateAutoGeneratedContainerClass : IPipelineStep<pMixinGeneratorPipelineState>
    {
        public const string AutoGeneratedClassName = "__pMixinAutoGenerated";

        public bool PerformTask(pMixinGeneratorPipelineState manager)
        {
            var autoGeneratedClass = new TypeDeclaration
            {
                ClassType = ClassType.Class,
                Modifiers = Modifiers.Private | Modifiers.Sealed,
                Name = AutoGeneratedClassName,
            };

            manager.AutoGeneratedContainerClass =
                manager.GeneratedClass.AddNestedType(autoGeneratedClass);

            return true;
        }
    }
}
