//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.6.0.457
//      for file pMixins\pMixins.Mvc.Recipes\Repository\Repository.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.Repository
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public partial class MyEntityRepository : global::pMixins.Mvc.Recipes.Repository.IReadById<global::pMixins.Mvc.Recipes.Repository.MyEntity>, global::pMixins.Mvc.Recipes.Repository.ICreate<global::pMixins.Mvc.Recipes.Repository.MyEntity>, pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements, pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.SqlReadByIdMixin__MyEntity__MasterWrapper pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__;
			public __pMixinAutoGenerated.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.SqlCreateMixin__MyEntity__MasterWrapper pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__;
			public __Mixins (MyEntityRepository target)
			{
				pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__ = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.SqlReadByIdMixin__MyEntity__MasterWrapper> ((pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements)target);
				pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__ = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.SqlCreateMixin__MyEntity__MasterWrapper> ((pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements)target);
			}
			[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.Repository.MyEntityRepository target)
			{
				pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.__ActivateMixinDependencies (target);
				pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			public sealed class pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__
			{
				public class SqlReadByIdMixin__MyEntity__MasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase, global::pMixins.Mvc.Recipes.Repository.IReadById<global::pMixins.Mvc.Recipes.Repository.MyEntity>
				{
					public SqlReadByIdMixin__MyEntity__MasterWrapper (pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.SqlReadByIdMixin__MyEntity__AbstractWrapper> (target);
						ReadByIdFunc = id => _mixinInstance.ReadById (id);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.SqlReadByIdMixin__MyEntity__AbstractWrapper _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.Func<global::System.Int32, global::pMixins.Mvc.Recipes.Repository.MyEntity> ReadByIdFunc {
						get;
						set;
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.Repository.MyEntityRepository target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntity (global::System.Data.SqlClient.SqlDataReader reader)
					{
						return base.ExecuteMethod ("MapEntity", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "reader",
								Type = typeof(global::System.Data.SqlClient.SqlDataReader),
								Value = reader
							}
						}, () => _mixinInstance.MapEntity_Public (reader));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ReadByIdStoredProcedureName {
						get {
							return base.ExecutePropertyGet ("ReadByIdStoredProcedureName", () => _mixinInstance.ReadByIdStoredProcedureName_Public);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ConnectionString {
						get {
							return base.ExecutePropertyGet ("ConnectionString", () => _mixinInstance.ConnectionString_Public);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public global::pMixins.Mvc.Recipes.Repository.MyEntity ReadById (global::System.Int32 id)
					{
						return base.ExecuteMethod ("ReadById", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "id",
								Type = typeof(global::System.Int32),
								Value = id
							}
						}, () => this.ReadByIdFunc (id));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams)
					{
						base.ExecuteVoidMethod ("ExecuteNonQuery", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "sParams",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = sParams
							}
						}, () => _mixinInstance.ExecuteNonQuery (spName, sParams));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
					{
						base.ExecuteVoidMethod ("ExecuteReader", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "sParams",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = sParams
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "readerCallback",
								Type = typeof(global::System.Action<global::System.Data.SqlClient.SqlDataReader>),
								Value = readerCallback
							}
						}, () => _mixinInstance.ExecuteReader (spName, sParams, readerCallback));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams)
					{
						return base.ExecuteMethod ("ExecuteScalar", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "sParams",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = sParams
							}
						}, () => _mixinInstance.ExecuteScalar (spName, sParams));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					global::pMixins.Mvc.Recipes.Repository.MyEntity global::pMixins.Mvc.Recipes.Repository.IReadById<global::pMixins.Mvc.Recipes.Repository.MyEntity>.ReadById (global::System.Int32 id)
					{
						return base.ExecuteMethod ("ReadById", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "id",
								Type = typeof(global::System.Int32),
								Value = id
							}
						}, () => ((global::pMixins.Mvc.Recipes.Repository.IReadById<global::pMixins.Mvc.Recipes.Repository.MyEntity>)_mixinInstance).ReadById (id));
					}
				}
			}
			public sealed class pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__
			{
				public class SqlCreateMixin__MyEntity__MasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase, global::pMixins.Mvc.Recipes.Repository.ICreate<global::pMixins.Mvc.Recipes.Repository.MyEntity>
				{
					public SqlCreateMixin__MyEntity__MasterWrapper (pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.SqlCreateMixin__MyEntity__AbstractWrapper> (target);
						CreateFunc = entity => _mixinInstance.Create (entity);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.SqlCreateMixin__MyEntity__AbstractWrapper _mixinInstance;
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.Func<global::pMixins.Mvc.Recipes.Repository.MyEntity, global::System.Boolean> CreateFunc {
						get;
						set;
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.Repository.MyEntityRepository target)
					{
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParameters (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
					{
						return base.ExecuteMethod ("MapEntityToSqlParameters", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "entity",
								Type = typeof(global::pMixins.Mvc.Recipes.Repository.MyEntity),
								Value = entity
							}
						}, () => _mixinInstance.MapEntityToSqlParameters_Public (entity));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String CreateStoredProcedureName {
						get {
							return base.ExecutePropertyGet ("CreateStoredProcedureName", () => _mixinInstance.CreateStoredProcedureName_Public);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					public global::System.String ConnectionString {
						get {
							return base.ExecutePropertyGet ("ConnectionString", () => _mixinInstance.ConnectionString_Public);
						}
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public global::System.Boolean Create (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
					{
						return base.ExecuteMethod ("Create", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "entity",
								Type = typeof(global::pMixins.Mvc.Recipes.Repository.MyEntity),
								Value = entity
							}
						}, () => this.CreateFunc (entity));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams)
					{
						base.ExecuteVoidMethod ("ExecuteNonQuery", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "sParams",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = sParams
							}
						}, () => _mixinInstance.ExecuteNonQuery (spName, sParams));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
					{
						base.ExecuteVoidMethod ("ExecuteReader", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "sParams",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = sParams
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "readerCallback",
								Type = typeof(global::System.Action<global::System.Data.SqlClient.SqlDataReader>),
								Value = readerCallback
							}
						}, () => _mixinInstance.ExecuteReader (spName, sParams, readerCallback));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					public global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams)
					{
						return base.ExecuteMethod ("ExecuteScalar", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "sParams",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = sParams
							}
						}, () => _mixinInstance.ExecuteScalar (spName, sParams));
					}
					[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
					[global::System.Diagnostics.DebuggerStepThrough]
					global::System.Boolean global::pMixins.Mvc.Recipes.Repository.ICreate<global::pMixins.Mvc.Recipes.Repository.MyEntity>.Create (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
					{
						return base.ExecuteMethod ("Create", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "entity",
								Type = typeof(global::pMixins.Mvc.Recipes.Repository.MyEntity),
								Value = entity
							}
						}, () => ((global::pMixins.Mvc.Recipes.Repository.ICreate<global::pMixins.Mvc.Recipes.Repository.MyEntity>)_mixinInstance).Create (entity));
					}
				}
			}
		}
		private __Mixins ____mixins;
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity> global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>>.MixinInstance {
			get {
				return __mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity> global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>>.MixinInstance {
			get {
				return __mixins.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__._mixinInstance;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity> (MyEntityRepository target) {
			return target.__mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__._mixinInstance;
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity> (MyEntityRepository target) {
			return target.__mixins.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__._mixinInstance;
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.__Shared
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISqlReadByIdMixin__MyEntity__Requirements : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.__Shared.ISharedRequirements
	{
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntity (global::System.Data.SqlClient.SqlDataReader reader);
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::System.String ReadByIdStoredProcedureName {
			get;
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::System.String ConnectionString {
			get;
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin
{
	public abstract class SqlReadByIdMixin__MyEntity__ProtectedMembersWrapper : global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>
	{
		public SqlReadByIdMixin__MyEntity__ProtectedMembersWrapper () : base ()
		{
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public new void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams)
		{
			base.ExecuteNonQuery (spName, sParams);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public new void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
		{
			base.ExecuteReader (spName, sParams, readerCallback);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public new global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams)
		{
			return base.ExecuteScalar (spName, sParams);
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin
{
	public class SqlReadByIdMixin__MyEntity__AbstractWrapper : SqlReadByIdMixin__MyEntity__ProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements _target;
		public SqlReadByIdMixin__MyEntity__AbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements target) : base ()
		{
			_target = target;
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		protected override global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntity (global::System.Data.SqlClient.SqlDataReader reader)
		{
			return _target.MapEntity (reader);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		protected override global::System.String ReadByIdStoredProcedureName {
			get {
				return _target.ReadByIdStoredProcedureName;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		protected override global::System.String ConnectionString {
			get {
				return _target.ConnectionString;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntity_Public (global::System.Data.SqlClient.SqlDataReader reader)
		{
			return this.MapEntity (reader);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		public global::System.String ReadByIdStoredProcedureName_Public {
			get {
				return this.ReadByIdStoredProcedureName;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		public global::System.String ConnectionString_Public {
			get {
				return this.ConnectionString;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.6.0.457")]
	public interface ISqlCreateMixin__MyEntity__Requirements : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.__Shared.ISharedRequirements
	{
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParameters (global::pMixins.Mvc.Recipes.Repository.MyEntity entity);
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::System.String CreateStoredProcedureName {
			get;
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		global::System.String ConnectionString {
			get;
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin
{
	public abstract class SqlCreateMixin__MyEntity__ProtectedMembersWrapper : global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>
	{
		public SqlCreateMixin__MyEntity__ProtectedMembersWrapper () : base ()
		{
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public new void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams)
		{
			base.ExecuteNonQuery (spName, sParams);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public new void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
		{
			base.ExecuteReader (spName, sParams, readerCallback);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public new global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] sParams)
		{
			return base.ExecuteScalar (spName, sParams);
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin
{
	public class SqlCreateMixin__MyEntity__AbstractWrapper : SqlCreateMixin__MyEntity__ProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements _target;
		public SqlCreateMixin__MyEntity__AbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements target) : base ()
		{
			_target = target;
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		protected override global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParameters (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
		{
			return _target.MapEntityToSqlParameters (entity);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		protected override global::System.String CreateStoredProcedureName {
			get {
				return _target.CreateStoredProcedureName;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		protected override global::System.String ConnectionString {
			get {
				return _target.ConnectionString;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParameters_Public (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
		{
			return this.MapEntityToSqlParameters (entity);
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		public global::System.String CreateStoredProcedureName_Public {
			get {
				return this.CreateStoredProcedureName;
			}
		}
		[global::CopaceticSoftware.pMixins.Attributes.MixedInMemberAttribute]
		public global::System.String ConnectionString_Public {
			get {
				return this.ConnectionString;
			}
		}
	}
}
