//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.1.12.350
//      for file D:\sandbox\pMixins\pMixins.Mvc.Recipes\Repository\Repository.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.Repository
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public partial class MyEntityRepository : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements, global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>>, global::pMixins.Mvc.Recipes.Repository.IReadById<global::pMixins.Mvc.Recipes.Repository.MyEntity>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>>, global::pMixins.Mvc.Recipes.Repository.ICreate<global::pMixins.Mvc.Recipes.Repository.MyEntity>
	{
		[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public readonly __pMixinAutoGenerated.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.SqlReadByIdMixin__MyEntity__MasterWrapper pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__;
			public readonly __pMixinAutoGenerated.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.SqlCreateMixin__MyEntity__MasterWrapper pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__;
			public __Mixins (MyEntityRepository host)
			{
				pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__ = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.SqlReadByIdMixin__MyEntity__MasterWrapper> ((global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements)host);
				pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__ = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.SqlCreateMixin__MyEntity__MasterWrapper> ((global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements)host);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (MyEntityRepository host)
			{
				pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.__ActivateMixinDependencies (host);
				pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.__ActivateMixinDependencies (host);
			}
		}
		private __Mixins _____mixins;
		private __Mixins ___mixins {
			get {
				if (null == _____mixins) {
					lock (__Mixins.____Lock) {
						if (null == _____mixins) {
							_____mixins = new __Mixins (this);
							_____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return _____mixins;
			}
		}
		[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
		private sealed class __pMixinAutoGenerated
		{
			[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
			public sealed class pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__
			{
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
				public sealed class SqlReadByIdMixin__MyEntity__MasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public global::System.Func<global::System.Int32, pMixins.Mvc.Recipes.Repository.MyEntity> ReadByIdFunc {
						get;
						set;
					}
					public readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.SqlReadByIdMixin__MyEntity__AbstractWrapper _mixinInstance;
					public SqlReadByIdMixin__MyEntity__MasterWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements mixinInstance)
					{
						_mixinInstance = base.TryActivateMixin<global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.SqlReadByIdMixin__MyEntity__AbstractWrapper> (mixinInstance);
						ReadByIdFunc = id => base.ExecuteMethod ("ReadById", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "id",
								Type = typeof(global::System.Int32),
								Value = id
							}
						}, () => _mixinInstance.ReadById (id));
						base.Initialize (mixinInstance, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (MyEntityRepository target)
					{
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
					{
						base.ExecuteVoidMethod ("ExecuteNonQuery", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "parameters",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = parameters
							}
						}, () => _mixinInstance.ExecuteNonQuery (spName, parameters));
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
					{
						base.ExecuteVoidMethod ("ExecuteReader", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "parameters",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = parameters
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "readerCallback",
								Type = typeof(global::System.Action<global::System.Data.SqlClient.SqlDataReader>),
								Value = readerCallback
							}
						}, () => _mixinInstance.ExecuteReader (spName, parameters, readerCallback));
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
					{
						return base.ExecuteMethod ("ExecuteScalar", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "parameters",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = parameters
							}
						}, () => _mixinInstance.ExecuteScalar (spName, parameters));
					}
					internal global::System.String ConnectionString {
						get {
							return base.ExecutePropertyGet ("ConnectionString", () => _mixinInstance.ConnectionString_Public);
						}
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntity (global::System.Data.SqlClient.SqlDataReader reader)
					{
						return base.ExecuteMethod ("MapEntity", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "reader",
								Type = typeof(global::System.Data.SqlClient.SqlDataReader),
								Value = reader
							}
						}, () => _mixinInstance.MapEntity_Public (reader));
					}
					internal global::System.String ReadByIdStoredProcedureName {
						get {
							return base.ExecutePropertyGet ("ReadByIdStoredProcedureName", () => _mixinInstance.ReadByIdStoredProcedureName_Public);
						}
						set {
							base.ExecutePropertySet ("ReadByIdStoredProcedureName", value, v => _mixinInstance.ReadByIdStoredProcedureName_Public = v);
						}
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::pMixins.Mvc.Recipes.Repository.MyEntity ReadById (global::System.Int32 id)
					{
						return ReadByIdFunc (id);
					}
				}
			}
			[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
			public sealed class pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__
			{
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
				public sealed class SqlCreateMixin__MyEntity__MasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public global::System.Func<global::pMixins.Mvc.Recipes.Repository.MyEntity, bool> CreateFunc {
						get;
						set;
					}
					public readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.SqlCreateMixin__MyEntity__AbstractWrapper _mixinInstance;
					public SqlCreateMixin__MyEntity__MasterWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements mixinInstance)
					{
						_mixinInstance = base.TryActivateMixin<global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.SqlCreateMixin__MyEntity__AbstractWrapper> (mixinInstance);
						CreateFunc = entity => base.ExecuteMethod ("Create", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "entity",
								Type = typeof(global::pMixins.Mvc.Recipes.Repository.MyEntity),
								Value = entity
							}
						}, () => _mixinInstance.Create (entity));
						base.Initialize (mixinInstance, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (MyEntityRepository target)
					{
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
					{
						base.ExecuteVoidMethod ("ExecuteNonQuery", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "parameters",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = parameters
							}
						}, () => _mixinInstance.ExecuteNonQuery (spName, parameters));
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
					{
						base.ExecuteVoidMethod ("ExecuteReader", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "parameters",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = parameters
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "readerCallback",
								Type = typeof(global::System.Action<global::System.Data.SqlClient.SqlDataReader>),
								Value = readerCallback
							}
						}, () => _mixinInstance.ExecuteReader (spName, parameters, readerCallback));
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
					{
						return base.ExecuteMethod ("ExecuteScalar", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "spName",
								Type = typeof(global::System.String),
								Value = spName
							},
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "parameters",
								Type = typeof(global::System.Data.SqlClient.SqlParameter[]),
								Value = parameters
							}
						}, () => _mixinInstance.ExecuteScalar (spName, parameters));
					}
					internal global::System.String ConnectionString {
						get {
							return base.ExecutePropertyGet ("ConnectionString", () => _mixinInstance.ConnectionString_Public);
						}
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParameters (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
					{
						return base.ExecuteMethod ("MapEntityToSqlParameters", new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.Parameter> {
							new global::CopaceticSoftware.pMixins.Interceptors.Parameter {
								Name = "entity",
								Type = typeof(global::pMixins.Mvc.Recipes.Repository.MyEntity),
								Value = entity
							}
						}, () => _mixinInstance.MapEntityToSqlParameters_Public (entity));
					}
					internal global::System.String CreateStoredProcedureName {
						get {
							return base.ExecutePropertyGet ("CreateStoredProcedureName", () => _mixinInstance.CreateStoredProcedureName_Public);
						}
						set {
							base.ExecutePropertySet ("CreateStoredProcedureName", value, v => _mixinInstance.CreateStoredProcedureName_Public = v);
						}
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					internal global::System.Boolean Create (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
					{
						return CreateFunc (entity);
					}
				}
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		protected void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
		{
			___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.ExecuteNonQuery (spName, parameters);
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		protected void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
		{
			___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.ExecuteReader (spName, parameters, readerCallback);
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		protected global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
		{
			return ___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.ExecuteScalar (spName, parameters);
		}
		protected virtual global::System.String ConnectionString {
			get {
				return ___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.ConnectionString;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		protected virtual global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntity (global::System.Data.SqlClient.SqlDataReader reader)
		{
			return ___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.MapEntity (reader);
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public virtual global::pMixins.Mvc.Recipes.Repository.MyEntity ReadById (global::System.Int32 id)
		{
			return ___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.ReadById (id);
		}
		protected virtual global::System.String ReadByIdStoredProcedureName {
			get {
				return ___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.ReadByIdStoredProcedureName;
			}
			set {
				___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.ReadByIdStoredProcedureName = value;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity> (MyEntityRepository target) {
			return target.___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__._mixinInstance;
		}
		global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity> global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>>.MixinInstance {
			get {
				return ___mixins.pMixins_Mvc_Recipes_Repository_SqlReadByIdMixin__pMixins_Mvc_Recipes_Repository_MyEntity__._mixinInstance;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		protected virtual global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParameters (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
		{
			return ___mixins.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.MapEntityToSqlParameters (entity);
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public virtual global::System.Boolean Create (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
		{
			return ___mixins.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.Create (entity);
		}
		protected virtual global::System.String CreateStoredProcedureName {
			get {
				return ___mixins.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.CreateStoredProcedureName;
			}
			set {
				___mixins.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__.CreateStoredProcedureName = value;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity> (MyEntityRepository target) {
			return target.___mixins.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__._mixinInstance;
		}
		global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity> global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>>.MixinInstance {
			get {
				return ___mixins.pMixins_Mvc_Recipes_Repository_SqlCreateMixin__pMixins_Mvc_Recipes_Repository_MyEntity__._mixinInstance;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public interface ISqlReadByIdMixin__MyEntity__Requirements
	{
		global::System.String ConnectionStringImplementation {
			get;
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntityImplementation (global::System.Data.SqlClient.SqlDataReader reader);
		global::System.String ReadByIdStoredProcedureNameImplementation {
			get;
			set;
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public abstract class SqlReadByIdMixin__MyEntity__ProtectedMembersWrapper : global::pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>
	{
		[global::System.Diagnostics.DebuggerStepThrough]
		public new void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
		{
			base.ExecuteNonQuery (spName, parameters);
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public new void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
		{
			base.ExecuteReader (spName, parameters, readerCallback);
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public new global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
		{
			return base.ExecuteScalar (spName, parameters);
		}
		public SqlReadByIdMixin__MyEntity__ProtectedMembersWrapper () : base ()
		{
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public class SqlReadByIdMixin__MyEntity__AbstractWrapper : SqlReadByIdMixin__MyEntity__ProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements _target;
		public SqlReadByIdMixin__MyEntity__AbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlReadByIdMixin.ISqlReadByIdMixin__MyEntity__Requirements target)
		{
			_target = target;
		}
		protected override global::System.String ConnectionString {
			get {
				return _target.ConnectionStringImplementation;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		protected override global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntity (global::System.Data.SqlClient.SqlDataReader reader)
		{
			return _target.MapEntityImplementation (reader);
		}
		protected override global::System.String ReadByIdStoredProcedureName {
			get {
				return _target.ReadByIdStoredProcedureNameImplementation;
			}
			set {
				_target.ReadByIdStoredProcedureNameImplementation = value;
			}
		}
		public global::System.String ConnectionString_Public {
			get {
				return this.ConnectionString;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::pMixins.Mvc.Recipes.Repository.MyEntity MapEntity_Public (global::System.Data.SqlClient.SqlDataReader reader)
		{
			return this.MapEntity (reader);
		}
		public global::System.String ReadByIdStoredProcedureName_Public {
			get {
				return this.ReadByIdStoredProcedureName;
			}
			set {
				this.ReadByIdStoredProcedureName = value;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public interface ISqlCreateMixin__MyEntity__Requirements
	{
		global::System.String ConnectionStringImplementation {
			get;
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParametersImplementation (global::pMixins.Mvc.Recipes.Repository.MyEntity entity);
		global::System.String CreateStoredProcedureNameImplementation {
			get;
			set;
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public abstract class SqlCreateMixin__MyEntity__ProtectedMembersWrapper : global::pMixins.Mvc.Recipes.Repository.SqlCreateMixin<global::pMixins.Mvc.Recipes.Repository.MyEntity>
	{
		[global::System.Diagnostics.DebuggerStepThrough]
		public new void ExecuteNonQuery (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
		{
			base.ExecuteNonQuery (spName, parameters);
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public new void ExecuteReader (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters, global::System.Action<global::System.Data.SqlClient.SqlDataReader> readerCallback)
		{
			base.ExecuteReader (spName, parameters, readerCallback);
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public new global::System.Object ExecuteScalar (global::System.String spName, global::System.Data.SqlClient.SqlParameter[] parameters)
		{
			return base.ExecuteScalar (spName, parameters);
		}
		public SqlCreateMixin__MyEntity__ProtectedMembersWrapper () : base ()
		{
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.12.350")]
	public class SqlCreateMixin__MyEntity__AbstractWrapper : SqlCreateMixin__MyEntity__ProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements _target;
		public SqlCreateMixin__MyEntity__AbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.Repository.MyEntityRepository.pMixins.Mvc.Recipes.Repository.SqlCreateMixin.ISqlCreateMixin__MyEntity__Requirements target)
		{
			_target = target;
		}
		protected override global::System.String ConnectionString {
			get {
				return _target.ConnectionStringImplementation;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		protected override global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParameters (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
		{
			return _target.MapEntityToSqlParametersImplementation (entity);
		}
		protected override global::System.String CreateStoredProcedureName {
			get {
				return _target.CreateStoredProcedureNameImplementation;
			}
			set {
				_target.CreateStoredProcedureNameImplementation = value;
			}
		}
		public global::System.String ConnectionString_Public {
			get {
				return this.ConnectionString;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public global::System.Data.SqlClient.SqlParameter[] MapEntityToSqlParameters_Public (global::pMixins.Mvc.Recipes.Repository.MyEntity entity)
		{
			return this.MapEntityToSqlParameters (entity);
		}
		public global::System.String CreateStoredProcedureName_Public {
			get {
				return this.CreateStoredProcedureName;
			}
			set {
				this.CreateStoredProcedureName = value;
			}
		}
	}
}
