//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.1.13.355
//      for file D:\Projects\sandbox\pMixins\pMixins.Mvc.Recipes\NonPublicNonParameterlessConstructor\NonPublicNonParameterlessConstructor.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
	public partial class NonPublicNonParameterlessConstructor : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin.IMixinRequirements, global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin.IAbstractMixinRequirements, global::CopaceticSoftware.pMixins.Infrastructure.IMixinConstructorRequirement<global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin>, global::CopaceticSoftware.pMixins.Infrastructure.IMixinConstructorRequirement<global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin.AbstractMixinAbstractWrapper>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin>
	{
		[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public readonly __pMixinAutoGenerated.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin.MixinMasterWrapper pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin;
			public readonly __pMixinAutoGenerated.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin.AbstractMixinMasterWrapper pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin;
			public __Mixins (NonPublicNonParameterlessConstructor host)
			{
				pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin.MixinMasterWrapper> ((global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin.IMixinRequirements)host);
				pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin.AbstractMixinMasterWrapper> ((global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin.IAbstractMixinRequirements)host);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (NonPublicNonParameterlessConstructor host)
			{
				pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin.__ActivateMixinDependencies (host);
				pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin.__ActivateMixinDependencies (host);
			}
		}
		private __Mixins _____mixins;
		private __Mixins ___mixins {
			get {
				if (null == _____mixins) {
					lock (__Mixins.____Lock) {
						if (null == _____mixins) {
							_____mixins = new __Mixins (this);
							_____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return _____mixins;
			}
		}
		[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
		private sealed class __pMixinAutoGenerated
		{
			[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
			public sealed class pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin
			{
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
				public abstract class MixinProtectedMembersWrapper : global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin
				{
					public MixinProtectedMembersWrapper () : base ()
					{
					}
					public MixinProtectedMembersWrapper (global::System.Int32 favoriteNumber) : base (favoriteNumber)
					{
					}
				}
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
				public class MixinAbstractWrapper : MixinProtectedMembersWrapper
				{
					private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin.IMixinRequirements _target;
					public MixinAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin.IMixinRequirements target) : base ()
					{
						_target = target;
					}
					public MixinAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin.IMixinRequirements target, global::System.Int32 favoriteNumber) : base (favoriteNumber)
					{
						_target = target;
					}
				}
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
				public sealed class MixinMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public readonly global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin _mixinInstance;
					public MixinMasterWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin.IMixinRequirements mixinInstance)
					{
						_mixinInstance = ((global::CopaceticSoftware.pMixins.Infrastructure.IMixinConstructorRequirement<global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin>)mixinInstance).InitializeMixin ();
						base.Initialize (mixinInstance, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (NonPublicNonParameterlessConstructor target)
					{
					}
					internal global::System.Int32 FavoriteNumber {
						get {
							return base.ExecutePropertyGet ("FavoriteNumber", () => _mixinInstance.FavoriteNumber);
						}
					}
				}
			}
			[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
			public sealed class pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin
			{
				[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
				public sealed class AbstractMixinMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin.AbstractMixinAbstractWrapper _mixinInstance;
					public AbstractMixinMasterWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin.IAbstractMixinRequirements mixinInstance)
					{
						_mixinInstance = ((global::CopaceticSoftware.pMixins.Infrastructure.IMixinConstructorRequirement<global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin.AbstractMixinAbstractWrapper>)mixinInstance).InitializeMixin ();
						base.Initialize (mixinInstance, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (NonPublicNonParameterlessConstructor target)
					{
					}
					internal global::System.Int32 AbstractFavoriteNumber {
						get {
							return base.ExecutePropertyGet ("AbstractFavoriteNumber", () => _mixinInstance.AbstractFavoriteNumber);
						}
					}
				}
			}
		}
		public global::System.Int32 FavoriteNumber {
			get {
				return ___mixins.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin.FavoriteNumber;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin (NonPublicNonParameterlessConstructor target) {
			return target.___mixins.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin._mixinInstance;
		}
		global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin>.MixinInstance {
			get {
				return ___mixins.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_Mixin._mixinInstance;
			}
		}
		public global::System.Int32 AbstractFavoriteNumber {
			get {
				return ___mixins.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin.AbstractFavoriteNumber;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin (NonPublicNonParameterlessConstructor target) {
			return target.___mixins.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin._mixinInstance;
		}
		global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin>.MixinInstance {
			get {
				return ___mixins.pMixins_Mvc_Recipes_NonPublicNonParameterlessConstructor_AbstractMixin._mixinInstance;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.Mixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
	public interface IMixinRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
	public interface IAbstractMixinRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
	public abstract class AbstractMixinProtectedMembersWrapper : global::pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin
	{
		public AbstractMixinProtectedMembersWrapper (global::System.Int32 favoriteNumber) : base (favoriteNumber)
		{
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.1.13.355")]
	public class AbstractMixinAbstractWrapper : AbstractMixinProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin.IAbstractMixinRequirements _target;
		public AbstractMixinAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.NonPublicNonParameterlessConstructor.pMixins.Mvc.Recipes.NonPublicNonParameterlessConstructor.AbstractMixin.IAbstractMixinRequirements target, global::System.Int32 favoriteNumber) : base (favoriteNumber)
		{
			_target = target;
		}
	}
}
