//----------------------------------------------------------------------- 
// <copyright file="BasicInterceptorSpec.cs" company="Copacetic Software"> 
// Copyright (c) Copacetic Software.  
// <author>Philip Pittle</author> 
// <date>Thursday, February 20, 2014 11:12:49 PM</date> 
// Licensed under the Apache License, Version 2.0,
// you may not use this file except in compliance with this License.
//  
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright> 
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CopaceticSoftware.pMixins.CodeGenerator.Tests.IntegrationTests.CompileTests.Interceptors;
using CopaceticSoftware.pMixins.TheorySandbox.COVERED.AsIsWrapper;

namespace CopaceticSoftware.pMixins.TheorySandbox.COVERED.Interceptors.InterceptorRequiresMixin
{
    /// <summary>
    /// Covered in:
    ///     <see cref="InterceptorWithMixinRequirementTest"/>
    /// </summary>
    public class MockLogMixin
    {
        public MockLogMixin() { Messages = new List<string>(); }

        public IList<string> Messages { get; private set; }

        public void AddLogMessage(string message)
        {
            Messages.Add(message);
        }
    }

    [InterceptorMixinRequirement(Mixin = typeof(MockLogMixin))]
    public class InterceptorWithRequirement : MixinInterceptorBase
    {
        public override void OnBeforeMethodInvocation(object sender, MethodEventArgs eventArgs)
        {
            eventArgs.Target.As<MockLogMixin>().AddLogMessage(
                "OnBeforeMethod: " + eventArgs.MemberName);
        }

        public override void OnAfterMethodInvocation(object sender, MethodEventArgs eventArgs)
        {
            eventArgs.Target.As<MockLogMixin>().AddLogMessage(
                "OnAfterMethod: " + eventArgs.MemberName);
        }
    }


    public class Mixin
    {
        public string Method()
        {
            return "Mixin";
        }
    }

    [BasicMixin(Target = typeof(Mixin), Interceptors = new Type[] { typeof(InterceptorWithRequirement) })]
    public partial class InterceptorRequiresMixinSpec
    { }

/*/////////////////////////////////////////
/// Generated Code
/////////////////////////////////////////*/

    public partial class InterceptorRequiresMixinSpec : IWrap<MockLogMixin>, IWrap<Mixin>
    {
        private class __pMixinAutoGenerated
        {
            public class CopaceticSoftware_pMixin_TheorySandbox_Interceptors_InterceptorRequiresMixin_Mixin
            {
                //don't need protected wrapper

                //don't need abstract wrapper

                public sealed class MasterWrapper : MasterWrapperBase
                {
                    public readonly Mixin Mixin;

                    public MasterWrapper(InterceptorRequiresMixinSpec target)
                    {
                        this.Mixin = new Mixin();

                        base.Initialize(target, Mixin,
                            new List<IMixinInterceptor>
                            {
                                //Need custom activator?
                                new DefaultMixinActivator().CreateInstance<InterceptorWithRequirement>()
                            });
                    }

                    public string Method()
                    {
                        return base.ExecuteMethod(
                            "Method",
                            new List<Parameter>(),
                            () => Mixin.Method());
                    }
                }
            }

            public class CopaceticSoftware_pMixin_TheorySandbox_Interceptors_InterceptorRequiresMixin_MockLogMixin
            {
                //don't need protected wrapper

                //don't need abstract wrapper

                public sealed class MasterWrapper : MasterWrapperBase
                {
                    public readonly MockLogMixin Mixin;

                    public MasterWrapper(InterceptorRequiresMixinSpec target)
                    {
                        this.Mixin = new MockLogMixin();

                        base.Initialize(target, Mixin,
                            new List<IMixinInterceptor>());
                    }

                    public IList<string> Messages
                    {
                        get
                        {
                            return base.ExecutePropertyGet(
                                "Message",
                                () => Mixin.Messages);
                        }
                    }

                    public void AddLogMessage(string message)
                    {
                        base.ExecuteVoidMethod(
                            "AddLogMessage",
                            new[]{
                                new Parameter{Name = "message", Type = typeof(string), Value = message}
                            },
                            () => Mixin.AddLogMessage(message));
                    }
                }
            }
        }

        private sealed partial class __Mixins
        {
            public static readonly global::System.Object ____Lock = new global::System.Object();

            public readonly __pMixinAutoGenerated.CopaceticSoftware_pMixin_TheorySandbox_Interceptors_InterceptorRequiresMixin_Mixin.MasterWrapper MixinMasterWrapper;
            public readonly __pMixinAutoGenerated.CopaceticSoftware_pMixin_TheorySandbox_Interceptors_InterceptorRequiresMixin_MockLogMixin.MasterWrapper MockLogMixinMasterWrapper;


            public __Mixins(InterceptorRequiresMixinSpec target)
            {
                this.MixinMasterWrapper =
                    new DefaultMixinActivator()
                        .CreateInstance<__pMixinAutoGenerated.CopaceticSoftware_pMixin_TheorySandbox_Interceptors_InterceptorRequiresMixin_Mixin.MasterWrapper>(
                            target);

                this.MockLogMixinMasterWrapper =
                    new DefaultMixinActivator()
                        .CreateInstance
                        <
                            __pMixinAutoGenerated.
                                CopaceticSoftware_pMixin_TheorySandbox_Interceptors_InterceptorRequiresMixin_MockLogMixin
                                .MasterWrapper>(
                                    target);
            }
        }

        private __Mixins _____mixins;
        private __Mixins ___mixins
        {
            get
            {
                if (null == _____mixins)
                {
                    lock (__Mixins.____Lock)
                    {
                        if (null == _____mixins)
                        {
                            _____mixins = new __Mixins(this);
                        }
                    }
                }
                return _____mixins;
            }
        }

        public string Method()
        {
            return ___mixins.MixinMasterWrapper.Method();
        }

        public IList<string> Messages
        {
            get
            {
                return ___mixins.MockLogMixinMasterWrapper.Messages;
            }
        }

        public void AddLogMessage(string message)
        {

            ___mixins.MockLogMixinMasterWrapper.AddLogMessage(message);
        }

        MockLogMixin IWrap<MockLogMixin>.GetWrappedItem()
        {
            return ___mixins.MockLogMixinMasterWrapper.Mixin;
        }

        Mixin IWrap<Mixin>.GetWrappedItem()
        {
            return ___mixins.MixinMasterWrapper.Mixin;
        }
    }
}