//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CopaceticSoftware.pMixins.CodeGenerator v0.5.1.379
//      for file pMixins\pMixins.Mvc.Recipes\MixinDependency\MixinDependency.cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.  
// </auto-generated> 
//------------------------------------------------------------------------------
namespace pMixins.Mvc.Recipes.MixinDependency
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.5.1.379")]
	public partial class MixinDependency : pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository.IRepositoryRequirements, pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator.IDecorator__Repository__Requirements, pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator.IOtherDecorator__Decorator__Repository____Requirements, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.MixinDependency.Repository>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>>, global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.MixinDependency.OtherDecorator<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>>>
	{
		private sealed class __Mixins
		{
			public static global::System.Object ____Lock = new global::System.Object ();
			public __pMixinAutoGenerated.pMixins_Mvc_Recipes_MixinDependency_Repository.RepositoryMasterWrapper pMixins_Mvc_Recipes_MixinDependency_Repository;
			public __pMixinAutoGenerated.pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository__.Decorator__Repository__MasterWrapper pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository__;
			public __pMixinAutoGenerated.pMixins_Mvc_Recipes_MixinDependency_OtherDecorator__pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository____.OtherDecorator__Decorator__Repository____MasterWrapper pMixins_Mvc_Recipes_MixinDependency_OtherDecorator__pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository____;
			public __Mixins (MixinDependency target)
			{
				pMixins_Mvc_Recipes_MixinDependency_Repository = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_MixinDependency_Repository.RepositoryMasterWrapper> ((pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository.IRepositoryRequirements)target);
				pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository__ = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository__.Decorator__Repository__MasterWrapper> ((pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator.IDecorator__Repository__Requirements)target);
				pMixins_Mvc_Recipes_MixinDependency_OtherDecorator__pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository____ = global::CopaceticSoftware.pMixins.Infrastructure.MixinActivatorFactory.GetCurrentActivator ().CreateInstance<__pMixinAutoGenerated.pMixins_Mvc_Recipes_MixinDependency_OtherDecorator__pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository____.OtherDecorator__Decorator__Repository____MasterWrapper> ((pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator.IOtherDecorator__Decorator__Repository____Requirements)target);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.MixinDependency.MixinDependency target)
			{
				pMixins_Mvc_Recipes_MixinDependency_Repository.__ActivateMixinDependencies (target);
				pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository__.__ActivateMixinDependencies (target);
				pMixins_Mvc_Recipes_MixinDependency_OtherDecorator__pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository____.__ActivateMixinDependencies (target);
			}
		}
		private sealed class __pMixinAutoGenerated
		{
			public sealed class pMixins_Mvc_Recipes_MixinDependency_Repository
			{
				public class RepositoryMasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public RepositoryMasterWrapper (pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository.IRepositoryRequirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository.RepositoryAbstractWrapper> (target);
						NameFuncGet = () => _mixinInstance.Name;
						NameFuncSet = value => _mixinInstance.Name = value;
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository.RepositoryAbstractWrapper _mixinInstance;
					public global::System.Func<global::System.String> NameFuncGet {
						get;
						set;
					}
					public global::System.Action<global::System.String> NameFuncSet {
						get;
						set;
					}
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.MixinDependency.MixinDependency target)
					{
					}
					internal global::System.String Name {
						get {
							return base.ExecutePropertyGet ("Name", () => NameFuncGet ());
						}
						set {
							base.ExecutePropertySet ("Name", value, v => NameFuncSet (v));
						}
					}
				}
			}
			public sealed class pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository__
			{
				public class Decorator__Repository__MasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public Decorator__Repository__MasterWrapper (pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator.IDecorator__Repository__Requirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator.Decorator__Repository__AbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository> _mixinInstance;
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.MixinDependency.MixinDependency target)
					{
						((global::CopaceticSoftware.pMixins.Infrastructure.IMixinDependency<global::pMixins.Mvc.Recipes.MixinDependency.Repository>)_mixinInstance).Dependency = target;
						((global::CopaceticSoftware.pMixins.Infrastructure.IMixinDependency<global::pMixins.Mvc.Recipes.MixinDependency.Repository>)_mixinInstance).OnDependencySet ();
					}
				}
			}
			public sealed class pMixins_Mvc_Recipes_MixinDependency_OtherDecorator__pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository____
			{
				public class OtherDecorator__Decorator__Repository____MasterWrapper : global::CopaceticSoftware.pMixins.Infrastructure.MasterWrapperBase
				{
					public OtherDecorator__Decorator__Repository____MasterWrapper (pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator.IOtherDecorator__Decorator__Repository____Requirements target)
					{
						_mixinInstance = base.TryActivateMixin<pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator.OtherDecorator__Decorator__Repository____AbstractWrapper> (target);
						base.Initialize (target, _mixinInstance, new global::System.Collections.Generic.List<global::CopaceticSoftware.pMixins.Interceptors.IMixinInterceptor> {

						});
					}
					public global::pMixins.Mvc.Recipes.MixinDependency.OtherDecorator<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>> _mixinInstance;
					[global::System.Diagnostics.DebuggerStepThrough]
					public void __ActivateMixinDependencies (pMixins.Mvc.Recipes.MixinDependency.MixinDependency target)
					{
						((global::CopaceticSoftware.pMixins.Infrastructure.IMixinDependency<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>>)_mixinInstance).Dependency = target;
						((global::CopaceticSoftware.pMixins.Infrastructure.IMixinDependency<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>>)_mixinInstance).OnDependencySet ();
					}
				}
			}
		}
		private __Mixins ____mixins;
		private __Mixins __mixins {
			get {
				if (null == ____mixins) {
					lock (__Mixins.____Lock) {
						if (null == ____mixins) {
							____mixins = new __Mixins (this);
							____mixins.__ActivateMixinDependencies (this);
						}
					}
				}
				return ____mixins;
			}
		}
		global::pMixins.Mvc.Recipes.MixinDependency.Repository global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.MixinDependency.Repository>.MixinInstance {
			get {
				return __mixins.pMixins_Mvc_Recipes_MixinDependency_Repository._mixinInstance;
			}
		}
		global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository> global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>>.MixinInstance {
			get {
				return __mixins.pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository__._mixinInstance;
			}
		}
		global::pMixins.Mvc.Recipes.MixinDependency.OtherDecorator<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>> global::CopaceticSoftware.pMixins.ConversionOperators.IContainMixin<global::pMixins.Mvc.Recipes.MixinDependency.OtherDecorator<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>>>.MixinInstance {
			get {
				return __mixins.pMixins_Mvc_Recipes_MixinDependency_OtherDecorator__pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository____._mixinInstance;
			}
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.MixinDependency.Repository (MixinDependency target) {
			return target.__mixins.pMixins_Mvc_Recipes_MixinDependency_Repository._mixinInstance;
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository> (MixinDependency target) {
			return target.__mixins.pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository__._mixinInstance;
		}
		[global::System.Diagnostics.DebuggerStepThrough]
		public static implicit operator global::pMixins.Mvc.Recipes.MixinDependency.OtherDecorator<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>> (MixinDependency target) {
			return target.__mixins.pMixins_Mvc_Recipes_MixinDependency_OtherDecorator__pMixins_Mvc_Recipes_MixinDependency_Decorator__pMixins_Mvc_Recipes_MixinDependency_Repository____._mixinInstance;
		}
		public virtual global::System.String Name {
			get {
				return __mixins.pMixins_Mvc_Recipes_MixinDependency_Repository.Name;
			}
			set {
				__mixins.pMixins_Mvc_Recipes_MixinDependency_Repository.Name = value;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.__Shared
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.5.1.379")]
	public interface ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.5.1.379")]
	public interface IRepositoryRequirements : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.__Shared.ISharedRequirements
	{
		global::System.String NameImplementation {
			get;
			set;
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository
{
	public abstract class RepositoryProtectedMembersWrapper : global::pMixins.Mvc.Recipes.MixinDependency.Repository
	{
		public RepositoryProtectedMembersWrapper () : base ()
		{
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository
{
	public class RepositoryAbstractWrapper : RepositoryProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository.IRepositoryRequirements _target;
		public RepositoryAbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Repository.IRepositoryRequirements target) : base ()
		{
			_target = target;
		}
		public override global::System.String Name {
			get {
				return _target.NameImplementation;
			}
			set {
				_target.NameImplementation = value;
			}
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.5.1.379")]
	public interface IDecorator__Repository__Requirements : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator
{
	public abstract class Decorator__Repository__ProtectedMembersWrapper : global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator
{
	public class Decorator__Repository__AbstractWrapper : Decorator__Repository__ProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator.IDecorator__Repository__Requirements _target;
		public Decorator__Repository__AbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.Decorator.IDecorator__Repository__Requirements target) : base ()
		{
			_target = target;
		}
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("pMixin", "0.5.1.379")]
	public interface IOtherDecorator__Decorator__Repository____Requirements : global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.__Shared.ISharedRequirements
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator
{
	public abstract class OtherDecorator__Decorator__Repository____ProtectedMembersWrapper : global::pMixins.Mvc.Recipes.MixinDependency.OtherDecorator<global::pMixins.Mvc.Recipes.MixinDependency.Decorator<global::pMixins.Mvc.Recipes.MixinDependency.Repository>>
	{
	}
}
namespace pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator
{
	public class OtherDecorator__Decorator__Repository____AbstractWrapper : OtherDecorator__Decorator__Repository____ProtectedMembersWrapper
	{
		private readonly global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator.IOtherDecorator__Decorator__Repository____Requirements _target;
		public OtherDecorator__Decorator__Repository____AbstractWrapper (global::pMixins.AutoGenerated.pMixins.Mvc.Recipes.MixinDependency.MixinDependency.pMixins.Mvc.Recipes.MixinDependency.OtherDecorator.IOtherDecorator__Decorator__Repository____Requirements target) : base ()
		{
			_target = target;
		}
	}
}
